# Generated by Django 5.0 on 2024-02-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_logging_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=64)),
                ('services', models.JSONField(max_length=8)),
                ('ticket_summary', models.FloatField()),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
