# Generated by Django 5.0 on 2024-03-04 10:12

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailServerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=128)),
                ('user_password', encrypted_model_fields.fields.EncryptedCharField()),
                ('message_from', models.CharField(max_length=128)),
                ('server', models.CharField(max_length=64)),
                ('port', models.IntegerField(default=587)),
                ('companyMail', models.CharField(max_length=128)),
            ],
        ),
    ]
