# Generated by Django 5.0 on 2024-02-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_text', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('step', models.IntegerField(default=0)),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('inherit_by', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('isOneGetService', models.BooleanField(default=False)),
                ('twoByOne', models.BooleanField(default=False)),
                ('twoByOneValue', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=256)),
                ('isAdditionalService', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='serviceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='parametersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0)),
                ('id_param', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.parameters')),
            ],
        ),
        migrations.AddField(
            model_name='parameters',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.servicelist'),
        ),
        migrations.CreateModel(
            name='templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=128)),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.servicelist')),
            ],
        ),
        migrations.CreateModel(
            name='templateParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('id_text_param', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.parameters')),
                ('id_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.templates')),
            ],
        ),
    ]
