# Generated by Django 5.0 on 2024-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='inherit_by',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
