# Generated by Django 4.2.4 on 2024-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_parameters_inherit_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
